services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: 
      - pip install --upgrade pip
      - pip install -r requirements1.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
